name: feature_flagix
description: "A new Flutter package project."
version: 1.0.0
homepage: https://github.com/Mustafa7Ibrahim/feature_flagix.git

environment:
  sdk: ">=3.2.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
